### ISSUE TITLE
Routing: always redirected to localhost:3000

### ISSUE THREAD

**Issue by eteubert** [podlove/radiator-cms#17]
Demo:

https://eric.co.de/u/locationbug.mp4

MacOS Firefox Developer Edition 67.0b19 (64-bit)

Might be related, log complains about duplicate `:id` used

```
 WARN  [vue-router] Duplicate param keys in route with path: "/networks/:id/podcasts/:id?"               10:43:39


 WARN  Argument "id" has invalid value null.                                                             10:43:39

  at _api__WEBPACK_IMPORTED_MODULE_0__.default.networks.getNetwork.then.response (server.js:4327:15)
  at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by Fischaela** [comment]
My guess: The `mounted()` method in the `default.vue` layout file is fired before the store gets its persistent refill from the local storage. 
Try to change the `beforeMounted()` method to `updated()` and check if `auth.isLoggedIn` has changed. If so, do not redirect. Do not know if that will work though ;)
