### ISSUE TITLE
As podcaster I want to import podcasts

### ISSUE THREAD

**Issue by Fischaela** [podlove/radiator-cms#60]

**Comment by Letty** [comment]
- [ ] Which result is expected by the user
- [ ] What are the steps to achieve this result
- [ ] What is the user guidance through the import process
- [ ] Design?

**Comment by Letty** [comment]
Steps:

1. Enter Feed URL
2. Receive the name, description, image and episode count from podcast. The user can check, if this is the expected podcast to import 
3. Import episode by episode
  a) Show progress (xx of yyy episodes loaded)
  b) Fill a report of missing data (xx episodes have no transcripts, yy have no chapter marks)
  c) Overview all episodes with encoding of filled and missing fields
  d) Allow the user to revisit this overview and edit the missing fields

**Comment by Letty** [comment]
First ideas:
![1024_Import-Podcast Step 1](https://user-images.githubusercontent.com/465678/60979072-5ddd7e80-a332-11e9-90e8-6a151cc8d332.png)
![1024_Import-Podcast Step 2](https://user-images.githubusercontent.com/465678/60979073-5ddd7e80-a332-11e9-8854-be2ee20c3b1f.png)
![1024_Import-Podcast Step 3](https://user-images.githubusercontent.com/465678/60979074-5ddd7e80-a332-11e9-8126-ef47f464925d.png)

**Comment by monkeydom** [comment]
Do we have a zeplin or other comment link for the mockups?

I do think step three should be not per episode (if those are indeed checkboxes where customization can take place) but per feed in general. If there is no other imput then I do think for now the only option probalby should be: 
* adjust the suggested short_id of the podcast
* allow the offical show url to be customized (the default would be //<radiatorinstance>>/<short_id>
* choose the audio format(s) to import (none should also be an option if one only wants to import the metadata and then push up the audio from somewhere else)
* also give the option to just keep the links to the media files as in the feed (we currrently don't have database entries for that, but this is something we need anyways)

**Comment by Letty** [comment]
> Do we have a zeplin or other comment link for the mockups? 

No, but i can create an account with the sketch file

> I do think step three should be not per episode (if those are indeed checkboxes where customization can take place) but per feed in general. 

My mistake, step three shows the imported episodes and where data is missing. For example you started chapter marks with episode 100 and transcripts in 120. Or you always had them, but they are missing in the feed. for whatever reason.
The User should know where something can be improved.

> If there is no other imput then I do think for now the only option probalby should be:
> 
> * adjust the suggested short_id of the podcast
> * allow the offical show url to be customized (the default would be //>/<short_id>
> * choose the audio format(s) to import (none should also be an option if one only wants to import the metadata and then push up the audio from somewhere else)
> * also give the option to just keep the links to the media files as in the feed (we currrently don't have database entries for that, but this is something we need anyways)

Ok this options would be something for step two.

**Comment by Letty** [comment]
- [ ] Can we customize the navigation for step handling?
